Added more tests for variables read and write

diff --git a/tests/switch/run-e2e-switch.sh.in b/tests/switch/run-e2e-switch.sh.in
--- a/tests/switch/run-e2e-switch.sh.in
+++ b/tests/switch/run-e2e-switch.sh.in
@@ -18,8 +18,13 @@ sleep 2 # let dummynodes start up
 sleep 3 # let switch start up
 
 # run e2e tests
-node_modules/jasmine-node/bin/jasmine-node .
-status=$?
+status=0
+for filename in *.js; do
+	echo "Running test set $filename"
+	node_modules/jasmine-node/bin/jasmine-node $filename
+	status=$(($status+$?))
+done
+echo "Failed $status test set(s)"
 
 # clean up switch
 [ -z "$(jobs -p)" ] || kill %%
